chore: Update URL pagination endpoint to always return 20 results
speakeasy-api/speakeasy-api-test-service pull request #13
Opened 2024-07-20 19:29 UTC by bflad

Previously, it would always return 0 results, which was confusing. For testing purposes, it shouldn't matter that the results are repeated in this context.

2024-07-20 19:52 UTC, simplesagar approved these changes

2024-07-22 13:48 UTC, 2ynn requested changes
@bflad I think it would be more interesting to have the length of `res.ResultArray` be proportional to the `attemps` value.

For example in HandleCursor the for loop depends on cursor:
https://github.com/speakeasy-api/speakeasy-api-test-service/blob/b224f69b69f0391ddf37866a9a880d0f86637c70/internal/pagination/service.go#L131
and the resulting length is  15, 5, 0 consecutively:
https://github.com/speakeasy-api/openapi-generation/blob/main/templates/templates/go/tests/primary/pagination_test.go.stmpl#L201

2024-07-22 14:16 UTC, bflad commented
@2ynn updated to return more interesting results:

```console
$ curl -XGET 'http://localhost:8080/pagination/url?attempts=3'
{"numPages":0,"resultArray":[0,1,2,3,4,5,6,7,8],"next":"http://localhost:8080/pagination/url?attempts=2"}
$ curl -XGET 'http://localhost:8080/pagination/url?attempts=2'
{"numPages":0,"resultArray":[0,1,2,3,4,5],"next":"http://localhost:8080/pagination/url?attempts=1"}
$ curl -XGET 'http://localhost:8080/pagination/url?attempts=1'
{"numPages":0,"resultArray":[0,1,2]}
$ curl -XGET 'http://localhost:8080/pagination/url?attempts=0'
{"numPages":0,"resultArray":[]}
```

Please let me know if you were wanting something different.

2024-07-22 15:17 UTC, 2ynn approved these changes

2024-07-22 15:17 UTC, merged